name: "Terraform Executa Modulo"

on:
  workflow_call:
    inputs:
      os_version:
        description: "Versão do sistema operacional"
        required: false
        default: "ubuntu-20.04"
        type: string
      aws_region:
        description: "Define a região AWS para a configuração das credenciais"
        required: true
        type: string
      tf_workspace:
        description: "Define o workspace em que o modulo será executado"
        required: false
        default: "default"
        type: string
      working_directory:
        description: "Diretório onde a pipeline irá atuar"
        required: false
        default: "."
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: "Credencial AWS"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "Credencial AWS"
        required: true

jobs:
  jobs_terraform:
    name: Terraform workflow
    runs-on: ${{ inputs.os_version }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lê versão do Terraform
        id: tf-version
        run: |
          TF_VERSION=$(sed -nr 's/\s*required_version\s+=\s+"(.*)"/\1/p' *.tf)
          echo "::set-output name=version::$TF_VERSION"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.tf-version.outputs.version }}

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format
        run: terraform fmt -check -diff

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Validação do tfsec
        run: |
          docker run --rm -v $PWD:/app -w /app tfsec/tfsec .
